typography_spectrum: 0.19107544096186757
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1820670689921826
  lightness: 0.4611793300136924
  saturation: 0.8799497142899781
  rhythmicContrast: 0.514437273144722
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6539669176563621
analytics:
  google: null
  facebook: null
  twitter: null
name: Reece.Fundraising
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: 'Doing something fun, for someone else'
purpose: []
